### ISSUE TITLE
Implement other Iterator traits where possible

### ISSUE THREAD

**Issue by rossmacarthur** [rossmacarthur/itermore#1]
- [x] [**DoubleEndedIterator**](https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html) An iterator able to yield elements from both ends.
- [x] [**ExactSizeIterator**](https://doc.rust-lang.org/std/iter/trait.ExactSizeIterator.html) An iterator that knows its exact length.
- [x] [**FusedIterator**](https://doc.rust-lang.org/std/iter/trait.FusedIterator.html) An iterator that always continues to yield None when exhausted.

**Comment by ripytide** [comment]
Would it be possible to implement `DoubleEndedIterator` for `windows_array()`? I think `slice`'s `windows()` method implements `DoubleEndedIterator`.
